#!/usr/bin/env bash

## https://people.sc.fsu.edu/~jburkardt/cpp_src/ivcon/ivcon.html
## sudo apt install openctm-tools
#ctmconv if of


for f in $(ls *.my); do
    d=/home/$USR/soft-slicers/slic3r
    LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libstdc++.so.6' $d/Slic3r-1.3.0-x86_64.AppImage \
        ${f//.my/.obj} --no-gui \
        --filament-diameter 1.75 --temperature 200 --bed-temperature 50 \
        --layer-height 0.2 --fill-density 75% \
        --output ${f//.my/.gcode}
        #--solid-infill-every-layers 1 \
        #--extrusion-width 0.35
        #--avoid-crossing-perimeters yes
done
